In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('/Users/klogg/dev/wiki_languages/quality_scores/test.csv',warn_bad_lines=True,error_bad_lines=False,index_col=None)

b'Skipping line 3423816: expected 12 fields, saw 15\n'

In [19]:
df.loc[df['project'] != 'None']

                                                           page_id  \
<module 'uuid' from '/Library/Frameworks/Python... 3822          1
                                                   3822          1
                                                   59658         1
                                                   99055         1
                                                   102119        1
                                                   116879        1
                                                   123566        1
                                                   151278        1
                                                   305265        1
                                                   366597        1
                                                   370324        1
                                                   443223        1

                                                                               namespace  \
<module 'uuid' from '/Library/Frameworks/Python... 3822                        Astronomy
                                                   3822                        Astronomy
                                                   59658                       John Cena
                                                   99055                  Sarojini Sahoo
                                                   102119  International System of Units
                                                   116879                   Powderfinger
                                                   123566                      Green Day
                                                   151278                          Tiger
                                                   305265                       Li Zehou
                                                   366597                   Anisul Hoque
                                                   370324                   Musa Ibrahim
                                                   443223                     Cherie Gil

                                                                                   title  \
<module 'uuid' from '/Library/Frameworks/Python... 3822                        Astronomy
                                                   3822                        Astronomy
                                                   59658                       John Cena
                                                   99055                  Sarojini Sahoo
                                                   102119  International System of Units
                                                   116879                   Powderfinger
                                                   123566                      Green Day
                                                   151278                          Tiger
                                                   305265                       Li Zehou
                                                   366597                   Anisul Hoque
                                                   370324                   Musa Ibrahim
                                                   443223                     Cherie Gil

                                                          archive  \
<module 'uuid' from '/Library/Frameworks/Python... 3822      None
                                                   3822      None
                                                   59658     None
                                                   99055     None
                                                   102119    None
                                                   116879    None
                                                   123566    None
                                                   151278    None
                                                   305265    None
                                                   366597    None
                                                   370324    None
                                                   443223    None

                                                                              user_text  \
<module 'uuid' from '/Library/Frameworks/Python... 3822                          Chenzw
                                                   3822    The Flying Spaghetti Monster
                                                   59658                  TrueCRaysball
                                                   99055                 117.200.224.13
                                                   102119                 121.91.91.101
                                                   116879            Fell on Black Days
                                                   123566            Fell on Black Days
                                                   151278                 70.166.103.18
                                                   305265               Mercurywoodrose
                                                   366597                        Hasive
                                                   370324                        Hasive
                                                   443223                Astigauthority

                                                          user_id revert  \
<module 'uuid' from '/Library/Frameworks/Python... 3822      8630  False
                                                   3822     13640  False
                                                   59658    11610  False
                                                   99055     None  False
                                                   102119    None  False
                                                   116879   26922  False
                                                   123566   26922  False
                                                   151278    None  False
                                                   305265  123897  False
                                                   366597  266147  False
                                                   370324  266147  False
                                                   443223  356141  False

                                                                            ts  \
<module 'uuid' from '/Library/Frameworks/Python... 3822    2008-04-30 03:58:32
                                                   3822    2008-05-15 14:45:56
                                                   59658   2008-01-21 18:26:45
                                                   99055   2008-03-14 13:23:02
                                                   102119  2008-04-10 05:22:03
                                                   116879  2008-09-27 11:59:31
                                                   123566  2008-09-23 14:15:23
                                                   151278  2009-04-17 13:25:02
                                                   305265  2011-08-17 21:09:18
                                                   366597  2012-10-17 05:30:22
                                                   370324  2012-11-10 02:33:20
                                                   443223  2014-03-18 05:52:50

                                                                                                     project  \
<module 'uuid' from '/Library/Frameworks/Python... 3822                                 [('everywiki', 'b')]
                                                   3822                                 [('everywiki', 'b')]
                                                   59658                         [('pro-wrestling', 'stub')]
                                                   99055        [('india', 'start'), ('biography', 'start')]
                                                   102119                                     [('isu', 'c')]
                                                   116879                                   [('rock', 'ga')]
                                                   123566                                    [('rock', 'b')]
                                                   151278  [('biography', 'ga'), ('usp-article', 'ga'), (...
                                                   305265                            [('biography', 'stub')]
                                                   366597                            [('biography', 'stub')]
                                                   370324                            [('biography', 'stub')]
                                                   443223  [('philippines', 'start'), ('biography', 'star...

                                                           quality
<module 'uuid' from '/Library/Frameworks/Python... 3822        NaN
                                                   3822        NaN
                                                   59658       NaN
                                                   99055       NaN
                                                   102119      NaN
                                                   116879      NaN
                                                   123566      NaN
                                                   151278      NaN
                                                   305265      NaN
                                                   366597      NaN
                                                   370324      NaN
                                                   443223      NaN

In [17]:
df1 = df.reset_index()

In [21]:
df1.loc[df1['level_1'] == 151278]

,level_0,level_1,page_id,namespace,title,archive,user_text,user_id,revert,ts,project,quality
2231544,<module 'uuid' from '/Library/Frameworks/Pytho...,151278,1,Tiger,Tiger,None,RyanCross,19514,False,2009-01-01 20:25:01,None,NaN
2231545,<module 'uuid' from '/Library/Frameworks/Pytho...,151278,1,Tiger,Tiger,None,70.166.103.18,None,False,2009-04-17 13:25:02,"[('biography', 'ga'), ('usp-article', 'ga'), (...",NaN
2231546,<module 'uuid' from '/Library/Frameworks/Pytho...,151278,1,Tiger,Tiger,None,161.53.192.162,None,True,2009-05-18 20:21:56,None,NaN